import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import { cn } from "@/lib/utils";
import NavigationMenu from "@/components/Layout/NavigationMenu";
import AsideMenu from "@/components/Aside/AsideMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, 'flex flex-row')}>

        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AsideMenu />
          <main className="flex flex-col w-full">

            <NavigationMenu />
            <div className="px-10 py-6">
              {children}
            </div>
          </main>
        </ThemeProvider>
      </body>
    </html >
  );
}
